[package]
name = "phos-helios-verifiable-api-client"
version.workspace = true
edition = "2021"
license.workspace = true
repository.workspace = true
description = "Verifiable API client for the Phos Helios fork"

[dependencies]
alloy.workspace = true
eyre.workspace = true
serde.workspace = true
serde_json.workspace = true
reqwest.workspace = true
reqwest-retry.workspace = true
reqwest-middleware.workspace = true
async-trait.workspace = true
tokio.workspace = true
url.workspace = true

# self crates
helios-verifiable-api-types = { package = "phos-helios-verifiable-api-types", version = "0.11.1" }
helios-common = { package = "phos-helios-common", version = "0.11.1" }
